// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXvakgavp4h_oKgqQDZJfQqBRcPmxseSk',
    appId: '1:20939572735:web:ddb3bce078207ab746d3ca',
    messagingSenderId: '20939572735',
    projectId: 'mubadrat-d19f4',
    authDomain: 'mubadrat-d19f4.firebaseapp.com',
    storageBucket: 'mubadrat-d19f4.firebasestorage.app',
    measurementId: 'G-9F7YXSQT4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW0BO2ikwXluD7U-pdVLIQ8PO-Uapj5o4',
    appId: '1:20939572735:android:165745af99a5f33d46d3ca',
    messagingSenderId: '20939572735',
    projectId: 'mubadrat-d19f4',
    storageBucket: 'mubadrat-d19f4.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwyMurQJayeIdaHbgVyZbucd8w-_jcvqs',
    appId: '1:20939572735:ios:93ef68c8caad28d446d3ca',
    messagingSenderId: '20939572735',
    projectId: 'mubadrat-d19f4',
    storageBucket: 'mubadrat-d19f4.firebasestorage.app',
    iosBundleId: 'com.example.bestOfTheBest',
  );
}
